steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/web-tdk-server:latest'
      - '.'

  # 2. Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/web-tdk-server:latest'

  # 3. Create/Update Migration Job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-migration-job'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'deploy'
      - 'migrate-tdk-db'
      - '--image'
      - 'gcr.io/$PROJECT_ID/web-tdk-server:latest'
      - '--region'
      - '${_REGION}'
      # VPC Settings
      - '--network'
      - 'default'
      - '--subnet'
      - 'default'
      - '--vpc-egress'
      - 'private-ranges-only'
      # -------------------------------------------------------------
      # ✅ Connection String สำหรับ PyMySQL + SSL + Private IP
      # -------------------------------------------------------------
      - '--set-env-vars'
      - 'DATABASE_URL=mysql+pymysql://admin_tdk:${_DB_PASSWORD}@${_DB_PRIVATE_IP}/tadika_db'
      # -------------------------------------------------------------
      - '--command'
      - 'python'
      - '--args'
      - 'run_migration.py'

  # 4. Execute Migration
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'run-migrations'
    waitFor: ['push-image', 'deploy-migration-job']
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'execute'
      - 'migrate-tdk-db'
      - '--region'
      - '${_REGION}'
      - '--wait'

  # 5. Deploy to Cloud Run Service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    waitFor: ['run-migrations']
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'web-tdk-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/web-tdk-server:latest'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--network'
      - 'default'
      - '--subnet'
      - 'default'
      - '--vpc-egress'
      - 'private-ranges-only'
      - '--add-cloudsql-instances'
      - '${_CLOUDSQL_INSTANCE}'
      - '--set-env-vars'
      # Service ปกติใช้ Unix Socket (ปลอดภัยอยู่แล้ว ไม่ต้องแก้)
      - 'DATABASE_URL=mysql+pymysql://admin_tdk:${_DB_PASSWORD}@/tadika_db?unix_socket=/cloudsql/${_CLOUDSQL_INSTANCE},JWT_SECRET_KEY=${_JWT_SECRET_KEY},CORS_ORIGINS=${_CORS_ORIGINS}'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: 'asia-southeast1'
  _MEMORY: '1Gi'
  _CPU: '1'
  _MAX_INSTANCES: '10'
  _CLOUDSQL_INSTANCE: 'tdk-proj:asia-southeast1:web-tdk-db'
  _DB_PASSWORD: 'Ihsan53295Ilham'
  _JWT_SECRET_KEY: 'dYY4eEoeLVpHVGnZrzP6boTfBIRCerJ7e59qzh1GYN0='
  _CORS_ORIGINS: '*'
  _DB_PRIVATE_IP: '10.124.176.3'