install-service:
	@echo "Installing service (requires sudo)"
	sudo ./install_service.sh $(USER)

start:
	./run_server.sh start

stop:
	./run_server.sh stop

status:
	./run_server.sh status

uninstall-service:
	@echo "Uninstalling service (requires sudo)"
	sudo ./uninstall_service.sh

create-owner:
	./run_create_owner.sh
