import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { X, GraduationCap, Calendar, Hash, ClipboardList, Plus, Loader2 } from 'lucide-react';

const CreateClassroomModal = ({
  isOpen,
  classroomStep,
  creatingClassroom,
  onCreateClassroom,
  onClose,
}) => {
  const { t } = useTranslation();
  const [gradeLevel, setGradeLevel] = useState('');
  const [roomNumber, setRoomNumber] = useState('');
  const [semester, setSemester] = useState(1);
  const [academicYear, setAcademicYear] = useState('');

  const generateClassName = () => {
    if (!gradeLevel) return '';
    if (roomNumber) return `${gradeLevel}/${roomNumber}`;
    return gradeLevel;
  };

  useEffect(() => {
    if (!isOpen) {
      setGradeLevel('');
      setRoomNumber('');
      setSemester(1);
      setAcademicYear('');
    }
  }, [isOpen]);

  const handleSubmit = async () => {
    await onCreateClassroom({
      name: generateClassName(),
      gradeLevel,
      roomNumber,
      semester,
      academicYear,
    });
    setGradeLevel('');
    setRoomNumber('');
    setSemester(1);
    setAcademicYear('');
  };

  if (!isOpen || classroomStep !== 'select') return null;

  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center p-4 sm:p-6 backdrop-blur-sm bg-slate-900/40 animate-in fade-in duration-300">
      <div className="bg-white w-full max-w-xl rounded-[2.5rem] shadow-2xl shadow-slate-900/20 overflow-hidden flex flex-col animate-in zoom-in-95 duration-300 max-h-[90vh]">
        {/* Header */}
        <div className="px-8 py-6 border-b border-slate-50 flex items-center justify-between bg-white sticky top-0 z-10">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-emerald-50 text-emerald-600 rounded-xl flex items-center justify-center">
              <Plus className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-lg font-black text-slate-800 tracking-tight leading-none">
                {t('admin.createNewClassroom')}
              </h3>
              <p className="text-[11px] font-bold text-slate-400 mt-1 uppercase tracking-widest">
                {t('admin.step1FillDetails')}
              </p>
            </div>
          </div>
          <button 
            onClick={onClose}
            className="w-10 h-10 flex items-center justify-center rounded-xl bg-slate-50 text-slate-400 hover:text-rose-500 hover:bg-rose-50 transition-all active:scale-95"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Body */}
        <div className="p-8 overflow-y-auto space-y-6">
          <div className="bg-emerald-50/50 p-4 rounded-2xl border border-emerald-100/50">
            <p className="text-sm font-black text-emerald-800 flex items-center gap-2">
              <ClipboardList className="w-4 h-4" />
              {t('admin.fillClassroomDetails')}
            </p>
            <p className="text-[11px] font-bold text-emerald-600/80 mt-1">
              {t('admin.classNameAutoGenerated')}
            </p>
          </div>

          <div className="space-y-4">
            <div className="space-y-1.5">
              <label className="text-[11px] font-black text-slate-400 uppercase tracking-widest flex items-center gap-2 px-1">
                <GraduationCap className="w-3.5 h-3.5" />
                {t('admin.gradeLevel')} <span className="text-rose-500">*</span>
              </label>
              <input 
                className="w-full h-14 px-6 bg-slate-50 border-2 border-transparent focus:border-emerald-500 focus:bg-white rounded-2xl text-slate-700 font-bold text-sm outline-none transition-all placeholder:text-slate-300"
                type="text"
                value={gradeLevel}
                onChange={e => setGradeLevel(e.target.value)}
                placeholder={t('admin.gradeExample')}
              />
              <p className="px-1 text-[10px] font-bold text-slate-400 italic">{t('admin.specifyGrade')}</p>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1.5">
                <label className="text-[11px] font-black text-slate-400 uppercase tracking-widest flex items-center gap-2 px-1">
                  <Calendar className="w-3.5 h-3.5" />
                  {t('admin.semester')}
                </label>
                <select 
                  className="w-full h-14 px-6 bg-slate-50 border-2 border-transparent focus:border-emerald-500 focus:bg-white rounded-2xl text-slate-700 font-bold text-sm outline-none transition-all appearance-none cursor-pointer"
                  value={semester}
                  onChange={e => setSemester(parseInt(e.target.value))}
                >
                  <option value={1}>{t('admin.semester1')}</option>
                  <option value={2}>{t('admin.semester2')}</option>
                </select>
              </div>

              <div className="space-y-1.5">
                <label className="text-[11px] font-black text-slate-400 uppercase tracking-widest flex items-center gap-2 px-1">
                  <Calendar className="w-3.5 h-3.5" />
                  {t('admin.academicYear')}
                </label>
                <input 
                  className="w-full h-14 px-6 bg-slate-50 border-2 border-transparent focus:border-emerald-500 focus:bg-white rounded-2xl text-slate-700 font-bold text-sm outline-none transition-all placeholder:text-slate-300"
                  type="text"
                  value={academicYear}
                  onChange={e => setAcademicYear(e.target.value)}
                  placeholder={t('admin.academicYearExample')}
                />
              </div>
            </div>

            <div className="space-y-1.5">
              <label className="text-[11px] font-black text-slate-400 uppercase tracking-widest flex items-center gap-2 px-1">
                <Hash className="w-3.5 h-3.5" />
                {t('admin.roomNumberOptional')}
              </label>
              <input 
                className="w-full h-14 px-6 bg-slate-50 border-2 border-transparent focus:border-emerald-500 focus:bg-white rounded-2xl text-slate-700 font-bold text-sm outline-none transition-all placeholder:text-slate-300"
                type="text"
                value={roomNumber}
                onChange={e => setRoomNumber(e.target.value)}
                placeholder={t('admin.roomNumberExample')}
              />
              <p className="px-1 text-[10px] font-bold text-slate-400 italic">{t('admin.roomNumberDescription')}</p>
            </div>
          </div>

          <div className="pt-4">
            <div className="bg-slate-50 rounded-2xl p-4 flex items-center justify-between">
              <span className="text-[11px] font-black text-slate-400 uppercase tracking-widest">{t('admin.classNamePreview')}</span>
              <span className="text-lg font-black text-emerald-600">{generateClassName() || '-'}</span>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="px-8 py-6 bg-slate-50/50 flex flex-col sm:flex-row gap-3">
          <button 
            type="button" 
            className="flex-1 h-12 bg-white hover:bg-slate-100 text-slate-600 rounded-xl font-black text-sm transition-all active:scale-95 border border-slate-100"
            onClick={onClose}
          >
            {t('common.cancel')}
          </button>
          <button 
            type="button" 
            className="flex-[2] h-12 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl font-black text-sm transition-all active:scale-95 shadow-lg shadow-emerald-200 flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed" 
            onClick={handleSubmit}
            disabled={creatingClassroom || !gradeLevel}
          >
            {creatingClassroom ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                {t('admin.creating')}
              </>
            ) : (
              <>
                <Plus className="w-4 h-4" />
                {t('admin.createClassroom')}
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
};

export default CreateClassroomModal;

